### Trip planner Tests
GET http://localhost:7071/api/candidateMatch

###

### login
POST http://localhost:7071/api/candidateMatch/auth/login
Content-Type: application/json

{
"username": "admin",
"password": "admin123"
}

###

### Get all candidates
GET http://localhost:7071/api/candidateMatch/candidates

###

### Get all candidates filtered
GET http://localhost:7071/api/candidateMatch/candidates?category=DEVOPS

###

### get by id
GET http://localhost:7071/api/candidateMatch/candidates/1

###

### Create candidate
POST http://localhost:7071/api/candidateMatch/candidates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjIzNDE3NjYsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6ImFkbWluIn0.GMPZMtWWmXiuGskS2iHx7_p_9WFT2ugZxv4kMfYCOwg

{
  "name": "test El-Mir",
  "phone": "13415801",
  "educationBackground": "Datamatiker",
  "candidateSkills": []
}

###

### Update
PUT http://localhost:7071/api/candidateMatch/candidates/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjIzNDE3NjYsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6ImFkbWluIn0.GMPZMtWWmXiuGskS2iHx7_p_9WFT2ugZxv4kMfYCOwg

{
    "name": "Mariam El-Mir Updated",
    "phone": "123000",
    "educationBackground": "Datamatiker - Updated",
    "candidateSkills": []
}


###

### Delete
DELETE http://localhost:7071/api/candidateMatch/candidates/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjIzNDE3NjYsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6ImFkbWluIn0.GMPZMtWWmXiuGskS2iHx7_p_9WFT2ugZxv4kMfYCOwg


###

###
PUT http://localhost:7071/api/candidateMatch/candidates/1/skills/1

###


### Skill ###

### Get all
GET http://localhost:7071/api/candidateMatch/skills

###

### get by id
GET http://localhost:7071/api/candidateMatch/skills/1

###

### Create candidate
GET http://localhost:7071/api/candidateMatch/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjIzNDE4OTgsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6ImFkbWluIn0.DUjzzIbqI5LYsiHLUpE-RhHDEgHGHDKwoktgIlPSBgI

{
  "name": "Docker",
  "category": "DEVOPS",
  "description": "Containerization tool"
}

###

### Update
PUT http://localhost:7071/api/candidateMatch/skills/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjIzNDE4OTgsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6ImFkbWluIn0.DUjzzIbqI5LYsiHLUpE-RhHDEgHGHDKwoktgIlPSBgI

{
  "name": "Java -updated",
  "category": "PROG_LANG",
  "description": "Java backend development -updated"
}


###

### Delete
DELETE http://localhost:7071/api/candidateMatch/skills/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hcmlhbSBFbG1pclwiIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjIzNDE4OTgsInJvbGVzIjoiQURNSU4iLCJ1c2VybmFtZSI6ImFkbWluIn0.DUjzzIbqI5LYsiHLUpE-RhHDEgHGHDKwoktgIlPSBgI

###